### ISSUE TITLE
terminate called after throwing an instance of 'file_not_found*

### ISSUE THREAD

**Issue by gr0sjean** [SuppenGeist/REIDE#1]
Hi,
after a make all, REIDE can't start.
src/reide_main.cc refer to a file (bin/testexe/testexe), file who do not exist afet compil.

Best regards

**Comment by SuppenGeist** [comment]
Hey,

im pretty surprised someone tried to build REIDE yet. This project is
mostly meant as a research project for me to learn c++ and reverese
engineering so dont expect it to do anything usefull anytime soon.
To your problem: there should be a c file in the folder bin/testexe which
you would have to compile seperatly with gcc. But testexe could be any elf
32 executable.

Sincerly
Johannes
Am 15.06.2015 22:02 schrieb "gr0sjean" <notifications@github.com>:
